export const TABLE_DATA_REQUEST = 'TABLE_DATA_REQUEST'
export const TABLE_DATA_SUCCESS = 'TABLE_DATA_SUCCESS'
export const TABLE_DATA_FAILURE = 'TABLE_DATA_FAILURE'
export const TABLE_ROW_DELETE = 'TABLE_ROW_DELETE'
export const ADD_NEW_RECORD = 'ADD_NEW_RECORD'
export const ADD_NEW_FAILED = 'ADD_NEW_FAILED'

export const SET_UPDATE_DATA = 'SET_UPDATE_DATA'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const RESET_STATE = 'RESET_STATE'

export const SEARCH_FILTER = 'SEARCH_FILTER'
